version: '3.1'
services:

  dbhackathon:
    image: postgres:11.9
    networks:
      - hackathon-o
    ports:
      - "57432:57432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DATABASE}"
    command: -p 57432

  flask-appl:
    image: cr-dw-flask-api
    restart: always
    networks:
      - hackathon-o
    ports:
      - "8000:8080"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DATABASE: "${POSTGRES_DATABASE}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      FLASK_APP: "${FLASK_APP}"
    volumes:
      - ../:/app/src
    build:
      context: ../
      dockerfile: Dockerfile
    command: bash -c "gunicorn wsgi:app --bind 0.0.0.0:8080 --log-level=debug --workers=4"


networks:
  hackathon-o:
    driver: bridge
