version: '3.1'
services:

  dbhackathon:
    image: mysql:5.7
    networks:
      - hackathon-o
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

    environment:
      MYSQL_DATABASE: "dementia"
      MYSQL_USER: "hackathon"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: 'password'



  flask-appl:
    image: cr-dw-flask-api
    restart: always
    networks:
      - hackathon-o
    ports:
      - "8000:8080"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DATABASE: "${POSTGRES_DATABASE}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      FLASK_APP: "${FLASK_APP}"
    volumes:
      - ../:/app/src
    build:
      context: ../
      dockerfile: Dockerfile
    command: bash -c "gunicorn wsgi:app --bind 0.0.0.0:8080 --log-level=debug --workers=4"

volumes:
  my-db:
networks:
  hackathon-o:
    driver: bridge

    
